module.exports = {
  transform: {
    '^.+\\.ts$': ['ts-jest', { tsconfig: 'tsconfig.test.json' }],
  },
  testMatch: ['<rootDir>/tests/unit/**/*.spec.ts'],
  coverageReporters: ['text', 'html'],
  collectCoverage: true,
  collectCoverageFrom: [
    '<rootDir>/src/**/*.ts',
    '!*/node_modules/',
    '!/vendor/**',
    '!*/common/dependencyRegistration.ts',
    '!*/common/tracing.ts',
    '!*/common/constants.ts',
    '!*/clients/callbackClient.ts**',
    '!*/clients/queueClient.ts**',
    '!**/controllers/**',
    '!**/routes/**',
    '!<rootDir>/src/index.ts',
    '!<rootDir>/src/containerConfig.ts',
    '!<rootDir>/src/app.ts',
    '!<rootDir>/src/serverBuilder.ts',
  ],
  coverageDirectory: '<rootDir>/coverage',
  reporters: [
    'default',
    ['jest-html-reporters', { multipleReportsUnitePath: './reports', pageTitle: 'unit', publicPath: './reports', filename: 'unit.html' }],
  ],
  rootDir: '../../../.',
  setupFiles: ['<rootDir>/tests/configurations/jest.setup.ts'],
  preset: 'ts-jest',
  testEnvironment: 'node',
  coverageThreshold: {
    global: {
      branches: 74,
      functions: 90,
      lines: 85,
      statements: 85,
    },
  },
};
