{{- $chartName := include "exporter-trigger.name" . -}}
{{- $tracingUrl := include "exporter-trigger.tracingUrl" . -}}
{{- $metricsUrl := include "exporter-trigger.metricsUrl" . -}}
{{- $tracingEnabled := include "exporter-trigger.tracingEnabled" . -}}
{{- $metricsEnabled := include "exporter-trigger.metricsEnabled" . -}}
{{- $metricsBuckets := include "exporter-trigger.metricsBuckets" . -}}
{{- $serviceUrls := (include "common.serviceUrls.merged" .) | fromYaml }}
{{- $jobManagement := (include "common.jobManagement.merged" .) | fromYaml }}
{{- $storage := (include "common.storage.merged" .) | fromYaml }}
{{- $configmapName := include "configmap.fullname" . }}
{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $configmapName }}
data:
  REQUEST_PAYLOAD_LIMIT: {{ .Values.env.requestPayloadLimit | quote }}
  RESPONSE_COMPRESSION_ENABLED: {{ .Values.env.responseCompressionEnabled | quote }}
  LOG_LEVEL: {{ .Values.env.logLevel | quote }}
  LOG_PRETTY_PRINT_ENABLED: {{ .Values.env.logPrettyPrintEnabled | quote }}
  TELEMETRY_TRACING_ENABLED: {{ $tracingEnabled | quote }}
  {{ if $tracingEnabled }}
  TELEMETRY_TRACING_URL: {{ $tracingUrl }}
  {{ end }}
  TELEMETRY_METRICS_ENABLED: {{ $metricsEnabled | quote }}
  {{ if $metricsEnabled }}
  TELEMETRY_METRICS_URL: {{ $metricsUrl }}
  TELEMETRY_METRICS_BUCKETS: {{ $metricsBuckets | toJson | quote }}
  {{ end }}
  JOB_MANAGER_URL: {{ $serviceUrls.jobManager | quote }}
  CLEANUP_EXPIRATION_DAYS: {{ .Values.env.cleanupExpirationDays | quote }}
  RASTER_CATALOG_MANAGER_URL: {{ $serviceUrls.catalogManager | quote }}
  JOB_DOMAIN: {{ $jobManagement.jobDomain | quote }}
  EXPORT_JOB_TYPE: {{ $jobManagement.exporter.jobType | quote }}
  TILES_TASK_TYPE: {{ $jobManagement.exporter.taskTilesType | quote }}
  HTTP_RETRY_ATTEMPTS: {{ .Values.env.httpRetry.attempts | quote }}
  HTTP_RETRY_DELAY: {{ .Values.env.httpRetry.delay | quote }}
  HTTP_RETRY_SHOULD_RESET_TIMEOUT: {{ .Values.env.httpRetry.shouldResetTimeout | quote }}
  DISABLE_HTTP_CLIENT_LOGS: {{ .Values.env.disableHttpClientLogs | quote }}
  TILES_PROVIDER: {{ $storage.tilesStorageProvider | quote }}
  DOWNLOAD_SERVER_URL: {{ $serviceUrls.downloadServer | quote }}
  FINALIZE_POLLING_TIMEOUT_MS: {{ .Values.env.finalizePollingTimeMS | quote }}
  JPEG_TILE_ESTIMATED_SIZE_IN_BYTES: {{ .Values.env.estimatedStorageCalculation.jpegTileEstimatedSizeInBytes | quote }}
  PNG_TILE_ESTIMATED_SIZE_IN_BYTES: {{ .Values.env.estimatedStorageCalculation.pngTileEstimatedSizeInBytes | quote }}
  STORAGE_FACTOR_BUFFER: {{ .Values.env.estimatedStorageCalculation.storageFactorBuffer | quote }}
  VALIDATE_STORAGE_SIZE: {{ .Values.env.estimatedStorageCalculation.validateStorageSize | quote }}
  QUEUE_JOB_MANAGER_BASE_URL: {{ $serviceUrls.jobManager | quote }}
  QUEUE_HEART_BEAT_MANAGER_BASE_URL: {{ $serviceUrls.heartbeatManager | quote }}
  QUEUE_DEQUEUE_FINALIZE_INTERVAL_MS: {{ .Values.env.queue.dequeueFinalizeIntervalMs | quote }}
  QUEUE_HEART_BEAT_INTERVAL_MS: {{ .Values.env.queue.heartbeatIntervalMs | quote }}
  FINALIZE_TASK_TYPE: {{ $jobManagement.exporter.taskFinalizeType | quote }}
  FINALIZE_TASKS_ATTEMPTS: {{ .Values.env.queue.finalizeTasksAttempts | quote }}
{{- end }}
